### ISSUE TITLE
Scan fails with error

### ISSUE THREAD

**Issue by sashank** [riramar/hsecscan#12]
We are getting the below error , any help greatly appreciated 

```
hsecscan -i -u https://google.com
Traceback (most recent call last):
  File "/usr/local/bin/hsecscan", line 11, in <module>
    load_entry_point('hsecscan==0.0.1', 'console_scripts', 'hsecscan')()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 479, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2703, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2321, in load
    return self.resolve()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2327, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.5/dist-packages/hsecscan/hsecscan.py", line 19
    print '>> REDIRECT INFO <<'
                              ^
SyntaxError: Missing parentheses in call to 'print'
```

**Comment by usb** [comment]
Python 2.x is required.

**Comment by sashank** [comment]
I have the same 

```
python
Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> 

```

**Comment by usb** [comment]
```python2 -m pip install hsecscan --user```

**Comment by riramar** [comment]
Hi @sashank ,
As @usb pointed probably hsecscan is running using Python3 instead of Python2.
How did you install it? Did you install through pip? Can you also check which pip version you are using?
Not sure if your default pip3 version can install a Python2 package. If you are using pip3 by default you can uninstall using pip3 and install using pip2 instead.
You can check the language is defined as python 2.7 from here https://pypi.org/project/hsecscan/.

**Comment by sashank** [comment]
Thanks could make it work using command shared by "usb"
