### ISSUE TITLE
problem faced while try to run hsecscan

### ISSUE THREAD

**Issue by ashvantraj16** [riramar/hsecscan#17]
Traceback (most recent call last):
  File "/usr/local/bin/hsecscan", line 5, in <module>
    from hsecscan.hsecscan import main
  File "/usr/local/lib/python3.7/dist-packages/hsecscan/hsecscan.py", line 19
    print '>> REDIRECT INFO <<'
                              ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('>> REDIRECT INFO <<')?

**Comment by riramar** [comment]
hsecscan doesn't support python3.
Please try again with python2.
